import { Gender } from "../enum/gender";
import { Currency } from "../enum/currency";
import { Size } from "../enum/size";
import { SuitColour } from "../enum/suit-colour";
import { Brand } from "../enum/brand";
import { Suit } from "../schemas/suit.schema";

const BASE_URL = "https://e-commerce-api-sigma-lilac.vercel.app";

export const initSuits: Suit[] = [
    {
        gender: Gender.Men,
        price: 150,
        currency: Currency.TL,
        primaryInfo: "M-Slim Fit Suit",
        secondaryInfo: "Perfect for formal occasions",
        tertiaryInfo: "",
        sizes: [Size.XS, Size.M],
        colour: SuitColour.Black,
        brand: Brand.Limehaus,
        available: true,
        imgPaths: [`${BASE_URL}/suits/id-1/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Men,
        price: 200,
        currency: Currency.TL,
        primaryInfo: "M-Classic Red Suit",
        secondaryInfo: "Ideal for special events",
        tertiaryInfo: "",
        sizes: [Size.S, Size.L],
        colour: SuitColour.Red,
        brand: Brand.MarcyDarcy,
        available: false,
        imgPaths: [`${BASE_URL}/suits/id-2/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Men,
        price: 400,
        currency: Currency.TL,
        primaryInfo: "M-Modern Blue Suit",
        secondaryInfo: "Suitable for business meetings",
        tertiaryInfo: "",
        sizes: [Size.XS, Size.XXL],
        colour: SuitColour.Blue,
        brand: Brand.Farah,
        available: true,
        imgPaths: [`${BASE_URL}/suits/id-3/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Men,
        price: 300,
        currency: Currency.TL,
        primaryInfo: "M-Elegant White Suit",
        secondaryInfo: "Perfect for weddings",
        tertiaryInfo: "",
        sizes: [Size.L, Size.XL],
        colour: SuitColour.White,
        brand: Brand.MarcyDarcy,
        available: true,
        imgPaths: [`${BASE_URL}/suits/id-4/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Men,
        price: 450,
        currency: Currency.TL,
        primaryInfo: "M-Casual Gray Suit",
        secondaryInfo: "Great for casual events",
        tertiaryInfo: "",
        sizes: [Size.S, Size.XXL],
        colour: SuitColour.Gray,
        brand: Brand.Limehaus,
        available: false,
        imgPaths: [`${BASE_URL}/suits/id-5/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Men,
        price: 600,
        currency: Currency.TL,
        primaryInfo: "M-Chic Pink Suit",
        secondaryInfo: "Adds a touch of elegance",
        tertiaryInfo: "",
        sizes: [Size.XS, Size.XL],
        colour: SuitColour.Pink,
        brand: Brand.MarcyDarcy,
        available: true,
        imgPaths: [`${BASE_URL}/suits/id-6/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Men,
        price: 800,
        currency: Currency.TL,
        primaryInfo: "M-Classic Blue Suit",
        secondaryInfo: "Timeless and sophisticated",
        tertiaryInfo: "",
        sizes: [Size.L, Size.XXL],
        colour: SuitColour.Blue,
        brand: Brand.Farah,
        available: true,
        imgPaths: [`${BASE_URL}/suits/id-7/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Men,
        price: 1200,
        currency: Currency.TL,
        primaryInfo: "M-Stylish Blue Suit",
        secondaryInfo: "Versatile and elegant",
        tertiaryInfo: "",
        sizes: [Size.S, Size.M],
        colour: SuitColour.Blue,
        brand: Brand.MarcyDarcy,
        available: false,
        imgPaths: [`${BASE_URL}/suits/id-8/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Men,
        price: 1400,
        currency: Currency.TL,
        primaryInfo: "M-Sophisticated Brown Suit",
        secondaryInfo: "Ideal for upscale events",
        tertiaryInfo: "",
        sizes: [Size.S, Size.XXL],
        colour: SuitColour.Brown,
        brand: Brand.Limehaus,
        available: true,
        imgPaths: [`${BASE_URL}/suits/id-9/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Men,
        price: 1800,
        currency: Currency.TL,
        primaryInfo: "M-Casual brown Suit",
        secondaryInfo: "A trendy and casual option",
        tertiaryInfo: "",
        sizes: [Size.S, Size.L],
        colour: SuitColour.Brown,
        brand: Brand.MarcyDarcy,
        available: true,
        imgPaths: [`${BASE_URL}/suits/id-10/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Women,
        price: 170,
        currency: Currency.TL,
        primaryInfo: "W-Slim Fit White Suit",
        secondaryInfo: "Perfect for formal occasions",
        tertiaryInfo: "",
        sizes: [Size.XS, Size.M],
        colour: SuitColour.White,
        brand: Brand.Limehaus,
        available: true,
        imgPaths: [`${BASE_URL}/suits/id-11/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Women,
        price: 300,
        currency: Currency.TL,
        primaryInfo: "W-Classic Yellow Suit",
        secondaryInfo: "Ideal for special events",
        tertiaryInfo: "",
        sizes: [Size.S, Size.L],
        colour: SuitColour.Yellow,
        brand: Brand.MarcyDarcy,
        available: false,
        imgPaths: [`${BASE_URL}/suits/id-12/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Women,
        price: 250,
        currency: Currency.TL,
        primaryInfo: "W-Modern Red Suit",
        secondaryInfo: "Suitable for business meetings",
        tertiaryInfo: "",
        sizes: [Size.XS, Size.XXL],
        colour: SuitColour.Red,
        brand: Brand.Farah,
        available: true,
        imgPaths: [`${BASE_URL}/suits/id-13/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Women,
        price: 700,
        currency: Currency.TL,
        primaryInfo: "W-Elegant White Suit",
        secondaryInfo: "Perfect for weddings",
        tertiaryInfo: "",
        sizes: [Size.L, Size.XL],
        colour: SuitColour.White,
        brand: Brand.MarcyDarcy,
        available: true,
        imgPaths: [`${BASE_URL}/suits/id-14/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Women,
        price: 350,
        currency: Currency.TL,
        primaryInfo: "W-Casual Gray Suit",
        secondaryInfo: "Great for casual events",
        tertiaryInfo: "",
        sizes: [Size.S, Size.XXL],
        colour: SuitColour.Gray,
        brand: Brand.Limehaus,
        available: false,
        imgPaths: [`${BASE_URL}/suits/id-15/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Women,
        price: 500,
        currency: Currency.TL,
        primaryInfo: "W-Chic Pink Suit",
        secondaryInfo: "Adds a touch of entertainment",
        tertiaryInfo: "",
        sizes: [Size.XS, Size.XL],
        colour: SuitColour.Pink,
        brand: Brand.MarcyDarcy,
        available: true,
        imgPaths: [`${BASE_URL}/suits/id-16/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Women,
        price: 800,
        currency: Currency.TL,
        primaryInfo: "W-Classic Black Suit",
        secondaryInfo: "Timeless and sophisticated",
        tertiaryInfo: "",
        sizes: [Size.L, Size.XXL],
        colour: SuitColour.Black,
        brand: Brand.Farah,
        available: true,
        imgPaths: [`${BASE_URL}/suits/id-17/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Women,
        price: 1700,
        currency: Currency.TL,
        primaryInfo: "W-Stylish Blue Suit",
        secondaryInfo: "Versatile and elegant",
        tertiaryInfo: "",
        sizes: [Size.S, Size.M],
        colour: SuitColour.Blue,
        brand: Brand.MarcyDarcy,
        available: false,
        imgPaths: [`${BASE_URL}/suits/id-18/img-1.png`],
        stock: 100,
    },
    {
        gender: Gender.Women,
        price: 1500,
        currency: Currency.TL,
        primaryInfo: "W-Sophisticated Brown Suit",
        secondaryInfo: "Ideal for upscale events",
        tertiaryInfo: "",
        sizes: [Size.S, Size.XXL],
        colour: SuitColour.Brown,
        brand: Brand.Limehaus,
        available: true,
        imgPaths: [`${BASE_URL}/suits/id-19/img-1.png`],
        stock: 100,
    },
];
